### ISSUE TITLE
Configurable background color and prefixed content

### ISSUE THREAD

**Issue by Zachu** [hkgnp/logseq-mermaid-plugin#1]
This is basically two separate feature requests but anyway here goes:

**Background color configuration**

Mermaid.ink provides `bgColor` URL parameter that could be used to set the background color to match the current theme. Personally I think we don't need any magic to parse it from the current theme but only let user to configure it statically.

I'm not comfortable with the Logseq config file yet, but I'm just imagining the plugin configuration to be something as this 
```yaml
bgColor: 2f3437
```

**Init directives configuration**

Mermaid also provides a way to set a theme and such using [Directives](https://github.com/mermaid-js/mermaid/blob/develop/docs/directives.md). It would be great to be able to set a default directives in configuration as well.

As an initial step I personally would be fine with just a configuration value that would always be prepended into the mermaid configuration before base64-encoding it to mermaid.ink. Next step would probably be to let user overwrite it per diagram and detect it in the plugin. If the code already has a directive, then the plugin would merge it with the configurable defaults

So the minimum viable product could be something like this
```yaml
prepend: '%%{init: {'theme': 'dark'}}%%'
```

or if we'd like to already get step towards the the better solution I could see it being something like this
```yaml
initDirective:
  theme: dark
```

**End result**

So I would like to have something like following configuration:
```yaml
bgColor: 2f3437
initDirective:
  theme: dark
```

And then a following mermaid diagram
```mermaid
graph TD
  Foo --> Bar
```

would produce following mermaid.ink link
https://mermaid.ink/img/ICAlJXtpbml0OiB7J3RoZW1lJzogJ2RhcmsnfX0lJQpncmFwaCBURAogIEZvbyAtLT4gQmFyCg==?bgColor=2f3437

**Comment by hkgnp** [comment]
FR delivered in [v1.0.5](https://github.com/hkgnp/logseq-mermaid-plugin/releases/tag/v1.0.5).

Instructions here: https://github.com/hkgnp/logseq-mermaid-plugin#changing-background-colour

**Comment by Zachu** [comment]
@hkgnp it seems that the color definition disappears when pressing render, so on the next render it returns back to default.

Other thing is that is there a possibility to read some sort of a plugin-specific configurations from a file or something that sorts? It's a bit cumbersome to input the background color for every single mermaid diagram, and possibly also go through all of them after changing the Logseq theme. Having a default background color in a file would fix these workflow issues.

And final thing, should I create another FR for the initDirective support?

**Comment by hkgnp** [comment]
Is your desired request to just have a permanent theme + bgColor entered for all graphs?

Or conditionally?

**Comment by Zachu** [comment]
Well permanent would be what I would want personally =) But knowing that all people do not work like I do I think overwriting possibility per graph could be something that someone could want. I don't have such needs for now at least.

**Comment by hkgnp** [comment]
> Well permanent would be what I would want personally =) But knowing that all people do not work like I do I think overwriting possibility per graph could be something that someone could want. I don't have such needs for now at least.

Try v1.0.9.

Instructions here: https://github.com/hkgnp/logseq-mermaid-plugin#option-2

**Comment by Zachu** [comment]
I think this broke the rendering again :sweat_smile: 
![image](https://user-images.githubusercontent.com/1262488/154030132-52f5ace5-da62-41ca-9595-186db7012a55.png)

With empty `{}` configuration it sends following request and gets `http400` as a response:
```http
GET https://mermaid.ink/img/JSV7aW5pdDogeyAndGhlbWUnOiB1bmRlZmluZWQgfSB9JSUgIGdyYXBoIFRECiAgRm9vIC0tPiBCYXIKYGBg
```

````bash
$ base64 -d <<< "JSV7aW5pdDogeyAndGhlbWUnOiB1bmRlZmluZWQgfSB9JSUgIGdyYXBoIFRECiAgRm9vIC0tPiBCYXIKYGBg"
%%{init: { 'theme': undefined } }%%  graph TD
  Foo --> Bar
```
````

With configuration being:
`$ cat ~/.logseq/settings/logseq-mermaid-plugin.json`
```json
{
  "theme": "dark",
  "colour": "black"
}
```

The request sent is following and it also gets `http400`:
```http
GET https://mermaid.ink/img/JSV7aW5pdDogeyAndGhlbWUnOiBkYXJrIH0gfSUlICBncmFwaCBURAogIEZvbyAtLT4gQmFyCmBgYA==
```

````bash
base64 -d <<< "JSV7aW5pdDogeyAndGhlbWUnOiBkYXJrIH0gfSUlICBncmFwaCBURAogIEZvbyAtLT4gQmFyCmBgYA=="
%%{init: { 'theme': dark } }%%  graph TD
  Foo --> Bar
```
````

So if I interpret this correctly, we are just missing a newline after the initDirective, but also appending the trailing \`\`\` there too. And I'm not sure, but the colour doesn't seem to get appended to the URL either.

**Comment by hkgnp** [comment]
Apologies! Completely misunderstood directives.

Please try 1.0.10!

Your plugin settings should also be (note how 'colour' is spelt and hexadecimal colours need to have the hash in front):
```
{
    "config": {
        "theme": "dark",
        "colour": "#2f3437"
    }
}
```

**Comment by Zachu** [comment]
You awesome great magnificent dude! It's perfect now =)
