### ISSUE TITLE
hide mermaid code?

### ISSUE THREAD

**Issue by notuntoward** [hkgnp/logseq-mermaid-plugin#10]
This is nice, but is there a way to hide the mermaid code, showing only the rendered graph?  It would be nice to keep the code within logseq so that I can change it later, and then re-render it.

**Comment by hkgnp** [comment]
You can just collapse the block, and it will hide the mermaid code.

**Comment by notuntoward** [comment]
Oh you're right.  I tried clicking the bullet symbol immediately above the code, which didn't do anything.  Not sure what that bullet is, but clicking the bullet immediately above the rendered image does what I want -- seems like it's kind of like a bullet title.
Thanks.
