### ISSUE TITLE
Hide "render" button when code is collapsed

### ISSUE THREAD

**Issue by notuntoward** [hkgnp/logseq-mermaid-plugin#11]
When the code window is collapsed, it would be nice if the "render" button was also collapsed.  Ideally, the logseq page would look like a printed page, without exposed code internals.

_Originally posted by @notuntoward in https://github.com/hkgnp/logseq-mermaid-plugin/issues/10#issuecomment-1172931994_

![image](https://user-images.githubusercontent.com/3851891/177010648-8ee4cee4-95ed-4b5c-aa7e-cabaf8b76d79.png)

**Comment by hkgnp** [comment]
Hi! Please use https://github.com/xyhp915/logseq-fenced-code-plus instead. It's far superior!
