### ISSUE TITLE
Feature Request: Kroki

### ISSUE THREAD

**Issue by aadityabhatia** [hkgnp/logseq-mermaid-plugin#13]
Support local [kroki](https://kroki.io/) server, which is capable of rendering mermaid among several other types of diagrams. It works like mermaid.ink but has a slightly different URL format and encoding. It is also supported by [mermaid.live](https://mermaid.live).

**Comment by hkgnp** [comment]
Please see the following from the README:

> The amazing xyhp915 built a local-only plugin that supports drawing of mermaid diagrams. Implentation is a lot smoother. [Link to the plugin](https://github.com/xyhp915/logseq-fenced-code-plus)

May be better to put your request there as I think the implementation is much cleaner.

**Comment by aadityabhatia** [comment]
Opened a [new feature request at logseq-fenced-code-plus](https://github.com/xyhp915/logseq-fenced-code-plus/issues/38). Thank you!
