### ISSUE TITLE
Output error messages on invalid Mermaid syntax

### ISSUE THREAD

**Issue by Zachu** [hkgnp/logseq-mermaid-plugin#2]
Currently the plugin just embeds a broken image if invalid mermaid syntax is provided. It would be great to get the error message outputted to the user.

Example:
```mermaid
graph TD
  Foo -> Bar
```

Produces following link https://mermaid.ink/img/ICBncmFwaCBURAogIEZvbyAtPiBCYXIK. This link outputs text `invalid encoded code` instead of image. In logseq it show as following:
![image](https://user-images.githubusercontent.com/1262488/153841777-3c75f02a-9eb5-4fc2-a55d-19a6a8fac1ec.png)

**Comment by hkgnp** [comment]
Fixed in v1.0.3.
