### ISSUE TITLE
Access to fetch at ... from origin 'lsp://logseq.io' has been blocked by CORS policy

### ISSUE THREAD

**Issue by hkgnp** [hkgnp/logseq-mermaid-plugin#4]
Ref: https://github.com/hkgnp/logseq-mermaid-plugin/issues/3#issuecomment-1039579549

Hi all, this is interesting. For those facing the CORS error, you can roll back to the previous version and I don't think you will face the issue. I was attempting to do a check on the validity of the mermaid issue and implemented a "fetch" to do so before the image is rendered.

@logseq-cldwalker do you happen to know what's `lsp://logseq.io` and where it is coming from?

**Comment by hkgnp** [comment]
@rubbsdecvik @logseq-cldwalker could you update to v1.0.4 and try again?

**Comment by Zachu** [comment]
It's been a while since my last javascript coding, but I think you could disable cors for the request in here https://github.com/hkgnp/logseq-mermaid-plugin/blob/550583db342bd3264333ed34c9e008d8990043b5/src/convert.ts by adding `{ mode: "no-cors" }

**Comment by Zachu** [comment]
Or maybe hmm... Without disabling cors you could add header `Access-Control-Allow-Origin: https://mermaid.ink` maybe?

**Comment by Zachu** [comment]
I tried to fiddle with these on the minified js but had no success though :( With `mode: "no-cors"` I got it to render the `There is an error with your mermaid syntax. Please rectify and render again.` message though but not the graph

**Comment by hkgnp** [comment]
`mode: "no-cors"` actually stops everything that cors does not allow so it will not help this issue since the source of the issue is about cors.

Changed my approach slightly. Could you try v1.0.6?

**Comment by Zachu** [comment]
Still nope :(

![image](https://user-images.githubusercontent.com/1262488/154017742-af3fda0d-13dd-4959-9795-e91803673449.png)

**Comment by hkgnp** [comment]
In that case, I think you just use 1.0.7. I've removed the check for broken images and will try to find a way without depending on a http request.

**Comment by Zachu** [comment]
Confirmed that the rendering works with 1.0.7

**Comment by hkgnp** [comment]
Noted that v1.0.8 [works](https://github.com/hkgnp/logseq-mermaid-plugin/issues/3#issuecomment-1040004564)

Now let's wait for @bepolymathe @logseq-cldwalker @rubbsdecvik to test!

**Comment by rubbsdecvik** [comment]
Running 1.0.10 
![image](https://user-images.githubusercontent.com/129744/154069758-892c50a9-e4fc-4a32-bfab-6dedbbc83e26.png)

Works like a charm! 
![image](https://user-images.githubusercontent.com/129744/154069823-c1038ab3-ab2d-4858-8729-222268519279.png)

**Comment by logseq-cldwalker** [comment]
1.0.10 works :)

**Comment by bepolymathe** [comment]
Same for me. It works with 1.0.10

**Comment by hkgnp** [comment]
Good to hear!
