### ISSUE TITLE
Some graph type not rendering, despite manual creating working on mermaid.ink

### ISSUE THREAD

**Issue by emms007** [hkgnp/logseq-mermaid-plugin#6]
Hello,

I can run "graph TD" without any problem, so I assume plugin installation is OK.
Upon running "sequence Diagram", the img tag is generated but the image link returns a "not found image".

Could be that the link is truncated?
Example source:
`
sequenceDiagram
    participant Alice
    participant Bob
    Alice->>John: Hello John, how are you?
    loop Healthcheck
        John->>John: Fight against hypochondria
    end
    Note right of John: Rational thoughts 
    John-->>Alice: Great!
    John->>Bob: How about you?
    Bob-->>John: Jolly good!

`

**Comment by hkgnp** [comment]
Please update to v1.1.1 and try again

**Comment by emms007** [comment]
... and we're good ! congratulations (again)!
