### ISSUE TITLE
Gantt chart unreadable

### ISSUE THREAD

**Issue by kevinkleine** [hkgnp/logseq-mermaid-plugin#8]
Great work :) I love it.
The Gantt chart render is so small that I can't read the text. I cant use the config to change it. Id like to be able to set font size and other properties, such as the ones mentioned here: https://mermaid-js.github.io/mermaid/#/gantt?id=configuration

**Comment by hkgnp** [comment]
Do you have a sample Gantt chart that I can use to test?
Apologies as I do not really use Gantt charts within mermaid.
Thanks!

**Comment by Zachu** [comment]
For me the gantt charts don't even render for some reason. I'm trying to put the first example from the linked site in

```
gantt
    title A Gantt Diagram
    dateFormat  YYYY-MM-DD
    section Section
    A task           :a1, 2014-01-01, 30d
    Another task     :after a1  , 20d
    section Another
    Task in sec      :2014-01-12  , 12d
    another task      : 24d
```
It seems to give me the reqular http400 "invalid encoded code"
```http
GET https://mermaid.ink/img/ICUle2luaXQ6IHsndGhlbWUnOiAnZGFyayd9fSUlIApnYW50dAogICAgdGl0bGUgQSBHYW50dCBEaWFncmFtCiAgICBkYXRlRm9ybWF0ICBZWVlZLU1NLURECiAgICBzZWN0aW9uIFNlY3Rpb24KICAgIEEgdGFzayAgICAgICAgICAgOmExLCAyMDE0LTAxLTAxLCAzMGQKICAgIEFub3RoZXIgdGFzayAgICAgOmFmdGVyIGExICAsIDIwZAogICAgc2VjdGlvbiBBbm90aGVyCiAgICBUYXNrIGluIHNlYyAgICAgIDoyMDE0LTAxLTEyICAsIDEyZAogICAgYW5vdGhlciB0YXNrICAgICAgOiAyNGQK 400
```

Regular flowchart seems to work though
```md
graph TD
    A-->B
    A-->C
    B-->D
    C-->D
```
```http
GET https://mermaid.ink/img/ICUle2luaXQ6IHsndGhlbWUnOiAnZGFyayd9fSUlIApncmFwaCBURAogICAgQS0tPkIKICAgIEEtLT5DCiAgICBCLS0-RAogICAgQy0tPkQK
```

**Comment by hkgnp** [comment]
Hi! Please use https://github.com/xyhp915/logseq-fenced-code-plus instead. It's far superior!
